**
!profile-retrieval-service/
!profile-retrieval-service/**

profile-retrieval-service/.env
profile-retrieval-service/.env.*
!profile-retrieval-service/.env.example

profile-retrieval-service/bin/
profile-retrieval-service/build/
profile-retrieval-service/dist/
profile-retrieval-service/coverage.out
profile-retrieval-service/*.cover
profile-retrieval-service/*.prof
profile-retrieval-service/*.test

profile-retrieval-service/.DS_Store
profile-retrieval-service/.idea/
profile-retrieval-service/.vscode/
